pipeline {
    agent {label "kritika"}

    stages {
        stage('Code') {
            steps {
                echo 'This is a cloning part'
                git url:"https://github.com/Kritika70/HTML-CSS-JavaScript-projects-for-beginners", branch:"main"
                echo "Cloning Successful"
            }
        }
        stage('Test'){
            steps{
                echo "There is no testing here"
                echo "Hello!"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploying to Apache server...."
                sh "sudo cp -r /home/ubuntu/workspace/practice-jenkins/projects/age-calculator/* /var/www/html/"
            }
        }
    }
    post{
        success{
            echo 'Deployment Successful!'
        }
        failure{
            echo 'Deployment failure'
        }
    }
}
